# Generated by Django 3.0.4 on 2020-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagemaster',
            name='id',
        ),
        migrations.AddField(
            model_name='usagemaster',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='usagemaster',
            name='management_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='管理番号（自動付与）'),
            preserve_default=False,
        ),
    ]
