# Generated by Django 3.0.4 on 2020-05-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200517_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('management_id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理番号（自動付与）')),
                ('date', models.DateField(blank=True, null=True, verbose_name='支払日時')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.UsageMaster', verbose_name='ジャンル')),
            ],
            options={
                'verbose_name': 'Usage',
            },
        ),
    ]
