# Generated by Django 3.0.4 on 2020-06-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
    ]
