# Generated by Django 3.0.4 on 2020-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_usage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagemaster',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ジャンル'),
        ),
    ]
